//
//  CryptoUtil.swift
//  OpenLink (parent app)
//
//  base64url codec (RFC 4648 §5, unpadded — the encoding PROTOCOL.md uses
//  for `fp`, `psk`, `parentId`, `proof` and `parentToken`), plus a
//  constant-time comparison used by the certificate pinner.
//

import Foundation
import CryptoKit

enum Base64URL {
    static func encode(_ data: Data) -> String {
        data.base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    /// Decodes base64url, and also tolerates standard base64 with or without
    /// padding — a QR generated by a slightly different encoder shouldn't
    /// make pairing fail mysteriously.
    static func decode(_ string: String) -> Data? {
        var normalized = string
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        let remainder = normalized.count % 4
        if remainder != 0 {
            normalized += String(repeating: "=", count: 4 - remainder)
        }
        return Data(base64Encoded: normalized)
    }
}

enum CryptoUtil {
    /// Compares two byte strings without an early exit.
    ///
    /// A certificate fingerprint isn't secret, so a timing side channel here
    /// leaks nothing on its own — but this is the one comparison the app's
    /// entire security model rests on, and a constant-time compare costs
    /// nothing, so it isn't worth reasoning about whether it's exploitable.
    static func constantTimeEquals(_ lhs: Data, _ rhs: Data) -> Bool {
        guard lhs.count == rhs.count else { return false }
        var difference: UInt8 = 0
        for index in 0..<lhs.count {
            difference |= lhs[lhs.startIndex + index] ^ rhs[rhs.startIndex + index]
        }
        return difference == 0
    }

    static func sha256(_ data: Data) -> Data {
        Data(SHA256.hash(data: data))
    }

    /// HMAC-SHA256 with a raw-byte key.
    static func hmacSHA256(key: Data, message: Data) -> Data {
        let symmetricKey = SymmetricKey(data: key)
        return Data(HMAC<SHA256>.authenticationCode(for: message, using: symmetricKey))
    }

    /// Cryptographically secure random bytes, used for `parentId`.
    static func randomBytes(count: Int) -> Data {
        var bytes = [UInt8](repeating: 0, count: count)
        let status = SecRandomCopyBytes(kSecRandomDefault, count, &bytes)
        if status == errSecSuccess {
            return Data(bytes)
        }
        // SecRandomCopyBytes essentially cannot fail on iOS, but fall back to
        // CryptoKit's CSPRNG rather than returning predictable bytes.
        return SymmetricKey(size: .init(bitCount: count * 8)).withUnsafeBytes { Data($0) }
    }
}
